version: '3'

services:
  tensorflow-jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./app/notebooks:/app/notebooks
      - ./app/models:/app/models
      - ./app/.env:/app/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]