version: '3'

services:
  tensorflow-jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./app:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]